name: Backend CI

on:
  push:
    branches: ["main"]

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:

    # Download code
    - name: Checkout
      uses: actions/checkout@v4


    # Install Java
    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'


    # Give permission to mvnw
    - name: Grant permission
      run: chmod +x mvnw


    # Build Spring Boot JAR
    - name: Build with Maven
      run: ./mvnw clean package -DskipTests


    # Verify JAR exists (VERY professional step)
    - name: Check target folder
      run: ls target


    # Build Docker Image
    - name: Docker Build
      run: docker build -t leavemate-backend .
