name: Backend CI

on:
  push:
    branches: ["main"]
    paths:
      - 'leavemate/**'   # change this if your backend folder name is different

jobs:
  build-backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./leavemate   # ⭐ VERY IMPORTANT

    steps:

    # Checkout repository
    - name: Checkout Code
      uses: actions/checkout@v4


    # Setup Java
    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: maven   # ⭐ speeds up builds


    # Make mvnw executable
    - name: Grant permission
      run: chmod +x mvnw


    # Build JAR
    - name: Build with Maven
      run: ./mvnw clean package -DskipTests


    # Confirm JAR exists
    - name: Check target folder
      run: ls target


    # Build Docker Image
    - name: Docker Build
      run: docker build -t leavemate-backend .
